{% set name = "litescope" %}
{% set version = "2024.08" %}
{% set sha256 = "e8dc9cc93f60491addf4191e5eb97390e766a0144efd716395115cffacaee4ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litescope_cli = litescope.software.litescope_cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex >=2024.04
    - migen

test:
  imports:
    - litescope
  commands:
    - litescope_cli --help

about:
  home: https://github.com/enjoy-digital/litescope
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable embedded FPGA logic analyzer
  description: Small footprint and configurable embedded FPGA logic analyzer
  dev_url: https://github.com/enjoy-digital/litescope

extra:
  recipe-maintainers:
    - timkpaine
