{% set name = "litescope" %}
{% set version = "2025.12" %}
{% set sha256 = "b8e2e32e43e506486de48603b040c99c640f4894e3999bd3f62ed59af39324c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litescope_cli = litescope.software.litescope_cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - litex ~={{ version }}*
    - migen

test:
  imports:
    - litescope
  requires:
    - python {{ python_min }}
  commands:
    - litescope_cli --help

about:
  home: https://github.com/enjoy-digital/litescope
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable embedded FPGA logic analyzer
  description: Small footprint and configurable embedded FPGA logic analyzer
  dev_url: https://github.com/enjoy-digital/litescope

extra:
  recipe-maintainers:
    - timkpaine
