schema_version: 1

context:
  name: litescope
  version: "2026.08"
  sha256: d94f90a74e0a5aff2df24ef6de05a5cd7dfa522163683d4cb32e863b9ba6ad21

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/enjoy-digital/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  python:
    entry_points:
      - litescope_cli = litescope.software.litescope_cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - litex ~=${{ version }}
    - migen

tests:
  - python:
      imports:
        - litescope
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - litescope_cli --help

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Small footprint and configurable embedded FPGA logic analyzer
  description: Small footprint and configurable embedded FPGA logic analyzer
  homepage: https://github.com/enjoy-digital/litescope
  repository: https://github.com/enjoy-digital/litescope

extra:
  recipe-maintainers:
    - timkpaine
